### ISSUE TITLE
The package ember-inflector@2.0.1 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by skiminock** [san650/ember-web-app#84]
Anyone has an idea??? It's occurring after `ember install ember-web-app`

Ember: 2.9.1
Node: 6.3.1

`    
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/lib/install.js:125:32
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/lib/install.js:268:7
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at cb (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
    at asyncMap (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
    at next (/Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:234:5)
    at /Users/skiminock/Documents/projects/spark/node_modules/npm/node_modules/read-installed/read-installed.js:179:7
    at LOOP (fs.js:1758:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by san650** [comment]
I've updated ember-cli not so long ago, maybe I made a mistake and forgot to update a dependency. I'll try to investigate this tomorrow.

Thanks for the issue report @skiminock.
